In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

file = pd.read_excel('C:/Data_/excel/data_jobs_salary_all.xlsx',sheet_name='maaz_1')
print(file)

                 job_title_short  \
0          Senior Data Scientist
1                  Data Engineer
2            Senior Data Analyst
3      Machine Learning Engineer
4                 Data Scientist
...                          ...
32667      Senior Data Scientist
32668               Data Analyst
32669             Data Scientist
32670               Data Analyst
32671             Data Scientist

                                               job_title     job_location  \
0      Senior Data Scientist Data and Analytics Perfo...   Bennington, NE
1                                     Data Engineer - MA         Mesa, AZ
2      Supervisory Information Technology Specialist ...   Alexandria, VA
3                    Machine Learning Research Scientist   Pittsburgh, PA
4                                    Data Scientist, AWS       Irving, TX
...                                                  ...              ...
32667                              Senior Data Scientist    Palo Alto, CA
32668  eCommerce Data Analyst | Hybrid Work | W2 Acce...       Austin, TX
32669    Clinical Data Visualization Specialist - Remote         Anywhere
32670                       Data Analyst/Report Writer 2       Austin, TX
32671  Data Science Product Manager - Recommendations...  Prague, Czechia

                job_via        job_schedule_type  job_work_from_home  \
0      via ZipRecruiter                Full-time               False
1            via Indeed                Full-time               False
2      via ZipRecruiter                Full-time               False
3       via Ai-Jobs.net                Full-time               False
4          via Snagajob  Full-time and Part-time               False
...                 ...                      ...                 ...
32667        via Indeed                Full-time               False
32668      via LinkedIn               Contractor               False
32669  via ZipRecruiter                Full-time                True
32670        via Adzuna                Full-time               False
32671   via Ai-Jobs.net                Full-time               False

                 search_location     job_posted_date  job_no_degree_mention  \
0                          Sudan 2023-04-24 09:51:15                  False
1                        Georgia 2023-03-13 12:51:23                   True
2        New York, United States 2023-07-05 07:03:38                   True
3        Illinois, United States 2023-04-13 16:05:41                  False
4           Texas, United States 2023-10-15 06:02:51                  False
...                          ...                 ...                    ...
32667  California, United States 2023-08-29 18:05:55                  False
32668       Texas, United States 2023-03-15 19:01:41                  False
32669  California, United States 2023-12-18 16:02:34                  False
32670       Texas, United States 2023-05-04 07:01:58                   True
32671                    Czechia 2023-03-31 20:02:52                  False

       job_health_insurance    job_country salary_rate  salary_year_avg  \
0                      True          Sudan        year         128050.0
1                      True  United States        year         140000.0
2                     False  United States        year         156000.0
3                      True  United States        year         140000.0
4                     False  United States        hour              NaN
...                     ...            ...         ...              ...
32667                  True  United States        year         191000.0
32668                 False  United States        hour              NaN
32669                  True  United States        hour              NaN
32670                 False  United States        hour              NaN
32671                 False        Czechia        year          89100.0

       salary_hour_avg                            company_name  \
0                  NaN                      Cox Communications
1                  NaN                           Worldgate LLC
2                  NaN  National Technical Information Service
3                  NaN                             Bosch Group
4            39.795002                          Presidio, Inc.
...                ...                                     ...
32667              NaN                                   Navan
32668        42.500000        TalentBurst, an Inc 5000 company
32669        55.000000                       Avispa Technology
32670        55.000000                                 My3Tech
32671              NaN                             Zeta Global

                                              job_skills
0      ['sql', 'python', 'aws', 'pyspark', 'tableau',...
1      ['sql', 'nosql', 'java', 'python', 'kafka', 's...
2                                                    NaN
3                              ['pytorch', 'tensorflow']
4      ['python', 'r', 'sql', 'c', 'aws', 'gcp', 'big...
...                                                  ...
32667  ['go', 'python', 'sql', 'numpy', 'pandas', 'te...
32668                                ['python', 'excel']
32669                           ['sas', 'sas', 'python']
32670      ['sas', 'sas', 'word', 'excel', 'sharepoint']
32671                                                NaN

[32672 rows x 16 columns]

In [ ]:
file.index.name='job_id'   #None will remove the index column
file
#file['job_title_short'].value_counts().plot(kind='barh').

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills
job_id,,,,,,,,,,,,,,,,
0,Senior Data Scientist,Senior Data Scientist Data and Analytics Perfo...,"Bennington, NE",via ZipRecruiter,Full-time,False,Sudan,2023-04-24 09:51:15,False,True,Sudan,year,128050.0,NaN,Cox Communications,"['sql', 'python', 'aws', 'pyspark', 'tableau',..."
1,Data Engineer,Data Engineer - MA,"Mesa, AZ",via Indeed,Full-time,False,Georgia,2023-03-13 12:51:23,True,True,United States,year,140000.0,NaN,Worldgate LLC,"['sql', 'nosql', 'java', 'python', 'kafka', 's..."
2,Senior Data Analyst,Supervisory Information Technology Specialist ...,"Alexandria, VA",via ZipRecruiter,Full-time,False,"New York, United States",2023-07-05 07:03:38,True,False,United States,year,156000.0,NaN,National Technical Information Service,NaN
3,Machine Learning Engineer,Machine Learning Research Scientist,"Pittsburgh, PA",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-13 16:05:41,False,True,United States,year,140000.0,NaN,Bosch Group,"['pytorch', 'tensorflow']"
4,Data Scientist,"Data Scientist, AWS","Irving, TX",via Snagajob,Full-time and Part-time,False,"Texas, United States",2023-10-15 06:02:51,False,False,United States,hour,NaN,39.795002,"Presidio, Inc.","['python', 'r', 'sql', 'c', 'aws', 'gcp', 'big..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32667,Senior Data Scientist,Senior Data Scientist,"Palo Alto, CA",via Indeed,Full-time,False,"California, United States",2023-08-29 18:05:55,False,True,United States,year,191000.0,NaN,Navan,"['go', 'python', 'sql', 'numpy', 'pandas', 'te..."
32668,Data Analyst,eCommerce Data Analyst | Hybrid Work | W2 Acce...,"Austin, TX",via LinkedIn,Contractor,False,"Texas, United States",2023-03-15 19:01:41,False,False,United States,hour,NaN,42.500000,"TalentBurst, an Inc 5000 company","['python', 'excel']"
32669,Data Scientist,Clinical Data Visualization Specialist - Remote,Anywhere,via ZipRecruiter,Full-time,True,"California, United States",2023-12-18 16:02:34,False,True,United States,hour,NaN,55.000000,Avispa Technology,"['sas', 'sas', 'python']"
32670,Data Analyst,Data Analyst/Report Writer 2,"Austin, TX",via Adzuna,Full-time,False,"Texas, United States",2023-05-04 07:01:58,True,False,United States,hour,NaN,55.000000,My3Tech,"['sas', 'sas', 'word', 'excel', 'sharepoint']"
32671,Data Scientist,Data Science Product Manager - Recommendations...,"Prague, Czechia",via Ai-Jobs.net,Full-time,False,Czechia,2023-03-31 20:02:52,False,False,Czechia,year,89100.0,NaN,Zeta Global,NaN

In [29]:
file.index.name=None
file_USA=file[file['job_country']=='United States']
file_USA.reset_index(inplace=True)  #reset_index will starreplacet the index where a skip value occur by the following.
file_USA

,index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills
0,1,Data Engineer,Data Engineer - MA,"Mesa, AZ",via Indeed,Full-time,False,Georgia,2023-03-13 12:51:23,True,True,United States,year,140000.0,NaN,Worldgate LLC,"['sql', 'nosql', 'java', 'python', 'kafka', 's..."
1,2,Senior Data Analyst,Supervisory Information Technology Specialist ...,"Alexandria, VA",via ZipRecruiter,Full-time,False,"New York, United States",2023-07-05 07:03:38,True,False,United States,year,156000.0,NaN,National Technical Information Service,NaN
2,3,Machine Learning Engineer,Machine Learning Research Scientist,"Pittsburgh, PA",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-13 16:05:41,False,True,United States,year,140000.0,NaN,Bosch Group,"['pytorch', 'tensorflow']"
3,4,Data Scientist,"Data Scientist, AWS","Irving, TX",via Snagajob,Full-time and Part-time,False,"Texas, United States",2023-10-15 06:02:51,False,False,United States,hour,NaN,39.795002,"Presidio, Inc.","['python', 'r', 'sql', 'c', 'aws', 'gcp', 'big..."
4,6,Data Engineer,Sr. Data Engineer (remote),Anywhere,via Indeed,Full-time,True,"Texas, United States",2023-10-26 19:07:59,False,True,United States,year,135000.0,NaN,MultiPlan Inc.,"['python', 'java', 'sql', 'nosql', 'mongodb', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25136,32666,Data Scientist,Principal Data Scientist,"Hartford, CT",via Ladders,Full-time,False,"New York, United States",2023-06-17 02:19:14,False,True,United States,year,150000.0,NaN,Cognizant Technology Solutions,NaN
25137,32667,Senior Data Scientist,Senior Data Scientist,"Palo Alto, CA",via Indeed,Full-time,False,"California, United States",2023-08-29 18:05:55,False,True,United States,year,191000.0,NaN,Navan,"['go', 'python', 'sql', 'numpy', 'pandas', 'te..."
25138,32668,Data Analyst,eCommerce Data Analyst | Hybrid Work | W2 Acce...,"Austin, TX",via LinkedIn,Contractor,False,"Texas, United States",2023-03-15 19:01:41,False,False,United States,hour,NaN,42.500000,"TalentBurst, an Inc 5000 company","['python', 'excel']"
25139,32669,Data Scientist,Clinical Data Visualization Specialist - Remote,Anywhere,via ZipRecruiter,Full-time,True,"California, United States",2023-12-18 16:02:34,False,True,United States,hour,NaN,55.000000,Avispa Technology,"['sas', 'sas', 'python']"
25140,32670,Data Analyst,Data Analyst/Report Writer 2,"Austin, TX",via Adzuna,Full-time,False,"Texas, United States",2023-05-04 07:01:58,True,False,United States,hour,NaN,55.000000,My3Tech,"['sas', 'sas', 'word', 'excel', 'sharepoint']"